services:
  app:
    image: stavshamir/springwolf-amqp-example:${SPRINGWOLF_VERSION}
    environment:
      AMQP_HOST: amqp
    links:
      - amqp
    ports:
      - "8080:8080"
    depends_on:
      - amqp

  amqp:
    image: rabbitmq:4.2-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
