version: '3'
services:
  app:
    image: stavshamir/springwolf-amqp-example:0.5.0
    links:
      - amqp
    ports:
      - "8080:8080"
    depends_on:
      - amqp

  amqp:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

