name: springwolf-kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/springwolf-kafka.yml'
      - 'springwolf-core/**'
      - 'springwolf-plugins/springwolf-kafka-plugin/**'
      - 'springwolf-examples/springwolf-kafka-example/**'
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup spectral
        run: |
          echo 'extends: ["spectral:asyncapi"]' > .spectral.yaml
      - name: Lint asyncapi.json with spectral
        uses: addnab/docker-run-action@v3
        with:
          image: stoplight/spectral:latest
          options: -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }}
          run: spectral lint --ruleset ./.spectral.yaml --fail-on-unmatched-globs ./springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew -p springwolf-plugins/springwolf-kafka-plugin test

      - name: Run integration tests
        run: ./gradlew -p springwolf-examples/springwolf-kafka-example test

      - name: Publish package
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publish -p springwolf-plugins/springwolf-kafka-plugin
        env:
          ORG_GRADLE_PROJECT_SNAPSHOT: true

          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEY}}
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}

          ORG_GRADLE_PROJECT_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
